# FeedbackFlow Application Configuration

# AWS Configuration
aws.region=us-east-1
aws.dynamodb.table=Feedbacks
aws.sns.topic.arn=arn:aws:sns:us-east-1:ACCOUNT_ID:FeedbacksCriticos
aws.ses.sender.email=noreply@feedbackflow.com
aws.ses.admin.email=admin@feedbackflow.com

# Application
app.name=FeedbackFlow
app.version=1.0.0